### PR TITLE
Move react and react-dom to devDependencies and increase their version ranges in peerDependencies (fixes #20)

### LINKED ISSUE #20: react, react-dom and prop-types shouldn't be dependencies
I've upgraded to `react@17.0.1` and got an `Invalid hook call` error on `useKonami`.

Screenshot with "Invalid hook call" error

Seems like this package requires `react` and `react-dom` as dependencies.

```sh
npm ls react
candidate-area-client@0.1.0 /home/vitorluizc/projects/trybe/student-journey-client
├── UNMET PEER DEPENDENCY react@17.0.1 
└─┬ react-konami-code@2.0.1-beta.1
  └── react@16.14.0 

npm ERR! peer dep missing: react@^0.14 || ^15 || ^16, required by html-react-parser@0.13.0
npm ERR! peer dep missing: react@^16.0.0, required by react-heroicons-ui@1.0.2
npm ERR! peer dep missing: react@^16.8.0, required by react-hook-form@5.7.2
npm ERR! peer dep missing: react@^16.13.1, required by react-konami-code@2.0.1-beta.1
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0 || ^16.0.0, required by react-lottie@1.2.3
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-text-mask@5.4.3
```

But it shouldn't. `react` and `react-dom` should be required in `peerDependencies`, and just imported as `devDependency` if you need to run tests, example etc.

It also throws an error because React.js 17 don't match `react` peer dependency range. But it doesn't seem to break with it.

https://github.com/vmarchesin/react-konami-code/blob/a3278a801a92f8bcd92fc43eae51164954bb6e37/package.json#L68-L71

### PR DESCRIPTION
**Pull request by VitorLuizC**
- Moves `react` and `react-dom` to `devDependencies`.
- Increase `react` and `react-dom` versions range in `peerDependencies`, to any version that supports hooks.

Fixes #20

### CODE REVIEW

**Comment by vmarchesin** [comment]
Hey, thanks for this fix. I tried this inside the `example ` folder but I still get the same error for the hook call. Perhaps I tried something and pushed a broken version a long time ago. Unfortunately I don't have time to fix it, but could you make sure that it works inside the `example` folder before merge? I updated it so it uses the local install, let me know if you need more info.

**Comment by VitorLuizC** [comment]
> Hey, thanks for this fix. I tried this inside the `example ` folder but I still get the same error for the hook call. Perhaps I tried something and pushed a broken version a long time ago. Unfortunately I don't have time to fix it, but could you make sure that it works inside the `example` folder before merge? I updated it so it uses the local install, let me know if you need more info.

I guess it happens because `npm link`, or the way you're importing the package inside the example, also imports package's dev dependencies. But I'll check and fix it.

**Comment by VitorLuizC** [comment]
Yeap, seems like `npm link` also brings `node_modules` with all packages, even dev dependencies.

```sh
➜  react-konami-code git:(master) ✗ cd example 
➜  example git:(master) ✗ npm ls react
react-konami-code-example@1.0.0 /home/vitorluizc/projects/react-konami-code/example
├── react@16.14.0 
└─┬ react-konami-code@2.0.1-beta.1 -> /home/vitorluizc/projects/react-konami-code
  └── react@16.14.0  extraneous

npm ERR! extraneous: react@16.14.0 /home/vitorluizc/projects/react-konami-code/example/node_modules/react-konami-code/node_modules/react
```

There's a lot of issues about it, and seems like the right way to do it is using `npm pack`.

```sh
➜  react-konami-code git:(master) ✗ cd ./example
➜  example git:(master) ✗ npm pack ../
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> react-konami-code@2.0.1-beta.1 prepublish /home/vitorluizc/projects/react-konami-code
> sh prepublish.sh


> react-konami-code@2.0.1-beta.1 build /home/vitorluizc/projects/react-konami-code
> webpack --mode production

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Hash: c33686a133ad127962b2
Version: webpack 4.43.0
Time: 1221ms
Built at: 03/14/2021 6:33:07 PM
    Asset      Size  Chunks             Chunk Names
Konami.js  6.77 KiB       0  [emitted]  main
Entrypoint main = Konami.js
[1] external {"root":"React","commonjs2":"react","commonjs":"react","amd":"react"} 42 bytes {0} [built]
[4] ./src/index.js + 2 modules 9.7 KiB {0} [built]
    | ./src/index.js 105 bytes [built]
    | ./src/Konami.jsx 7.2 KiB [built]
    | ./src/useKonami.js 2.39 KiB [built]
    + 3 hidden modules
npm notice 
npm notice 📦  react-konami-code@2.0.1-beta.1
npm notice === Tarball Contents === 
npm notice 15B   .tool-versions  
npm notice 1.1kB LICENSE         
npm notice 6.9kB dist/Konami.js  
npm notice 1.8kB package.json    
npm notice 1.1kB CHANGELOG.md    
npm notice 5.1kB README.md       
npm notice 545B  dist/Konami.d.ts
npm notice === Tarball Details === 
npm notice name:          react-konami-code                       
npm notice version:       2.0.1-beta.1                            
npm notice filename:      react-konami-code-2.0.1-beta.1.tgz      
npm notice package size:  6.8 kB                                  
npm notice unpacked size: 16.6 kB                                 
npm notice shasum:        7b52ac104dd49a2ff9cbe83d4d45f6f47eae6420
npm notice integrity:     sha512-zMsFwdPcM08lf[...]1riVW47hfZ/Fg==
npm notice total files:   7                                       
npm notice 
react-konami-code-2.0.1-beta.1.tgz
➜  example git:(master) ✗ npm i react-konami-code-2.0.1-beta.1.tgz
npm WARN react-konami-code-example@1.0.0 No repository field.
npm WARN react-konami-code-example@1.0.0 No license field.

+ react-konami-code@2.0.1-beta.1
added 9 packages from 4 contributors and audited 9 packages in 1.599s
found 0 vulnerabilities
```

It will install package exactly like if it was published to npm.

```sh
➜  example git:(master) ✗ npm ls react
react-konami-code-example@1.0.0 /home/vitorluizc/projects/react-konami-code/example
└── react@16.14.0 
```

Now its working fine!

screenshot with react-konami-code hook working fine

**Comment by VitorLuizC** [comment]
Você é brasileiro? auhsuahus

**Comment by vmarchesin** [comment]
Sou sim, mas pra manter as issues e PRs legíveis pra todo mundo é melhor manter o inglês :D 

Testei aqui e funcionou, obrigado pelo fix!
I tested here and it worked, thanks a lot for the fix!

**Comment by vmarchesin** [comment]
Version `2.1.0` is now released with the fix.

**Pull request merged**
